#### Numpy
    * Numpy is core data science library for matematical/scietific computing in Python. It provides a high-performance multidimentional array object and for working with array.
    * Numpy provides fast built-in object (nd-array).

In [1]:
import numpy as np

#### Numpy Array

In [2]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])    # Create a rank 1 numpy array
display(arr)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
# array - int8, int16, int32, int64
arr.dtype    # size in bits of each element of numpy array

dtype('int32')

In [5]:
arr.itemsize   # size of each element from an array 

4

In [6]:
arr.shape      # Shape returns a tuple listing length of the array along each dimensions

(8,)

In [7]:
print(arr.ndim)

1


In [8]:
print(arr.nbytes)    # return number of bytes used by data of the n-d array

32


#### Array Operations
    * Simple Array Math Operations.

In [12]:
a = np.array([10, 20, 30, 40, 50, 60, 70], dtype = 'int64')
b = np.array([1, 2, 3, 4, 5, 6, 7])

# element by element addition or subtraction
print(a + b)

[11 22 33 44 55 66 77]


In [13]:
print(a * b)

[ 10  40  90 160 250 360 490]


In [14]:
print(a ** b)

[           10           400         27000       2560000     312500000
   46656000000 8235430000000]


In [16]:
# Return evenly spaced values within given interval
# Create an array from 0 to 10
# arange (start, stop, step size)
np.arange(0, 11, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
# start, stop, step
np.arange(1., 16., 2)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15.])

#### Exercise 1: Why Numpy array are Better than Lists

In [20]:
import time
import numpy as np

array_size = 1000000
def python_version():
    # start time
    t1 = time.time()
    X = range(array_size)
    Y = range(array_size)
    # Element by element addition
    Z = [ X[i] + Y[i] for i in range(len(X))]
    return time.time() - t1

def numpy_version():
    # start time
    t1 = time.time()
    X = np.arange(array_size)
    Y = np.arange(array_size)
    Z = X + Y
    return time.time() - t1

t1 = python_version()
t2 = numpy_version()

print("Numpy in this example is : " + str(t1/t2) + "Faster")

Numpy in this example is : 69.19820449414041Faster


In [21]:
print(t1, t2)

0.3068983554840088 0.004435062408447266


In [23]:
distance_list = [10, 15, 18, 19, 21, 23]
time_list = [.20, .43, .55, 1.1, .59, 1.2]

speed = distance_list / time_list

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [25]:
distance_arr = np.array([10, 15, 18, 19, 21, 23])
time_arr = np.array([.20, .43, .55, 1.1, .59, 1.2])

speed_arr = distance_arr / time_arr
speed_arr

array([50.        , 34.88372093, 32.72727273, 17.27272727, 35.59322034,
       19.16666667])

#### Types of Numpy Array

In [26]:
# Create a 1-D Array
arr_1 = np.array([10, 15, 18, 19, 21, 25])

In [27]:
# Create a 2-D Array - Matrix
arr_2 = np.array([[1, 5, 8, 9, 11, 15],
                  [10, 15, 18, 19, 21, 25]])
print(arr_2)

[[ 1  5  8  9 11 15]
 [10 15 18 19 21 25]]


In [28]:
# shape = (rows, columns)
arr_2.shape

(2, 6)

In [29]:
arr_2.dtype

dtype('int32')

In [30]:
# Dimension of array
arr_2.ndim

2

In [35]:
# row index = 1
arr_2[1][2]

18

In [42]:
# Indexing of 2-D Array
arr_2[1][4]
# Alternative
arr_2[-1][-2]

21

#### Three-Dimentional Array

In [43]:
arr_3 = np.array([[[0, 1, 2, 3, 4, 5],
                   [10, 11, 12, 13, 14, 15],
                   [16, 17, 21, 32, 23, 19]],
                 
                  [[0, 1, 2, 3, 4, 5],
                   [10, 11, 12, 13, 14, 15],
                   [16, 17, 21, 32, 23, 19]],
                  
                  [[0, 1, 2, 3, 4, 5],
                   [10, 11, 12, 13, 14, 15],
                   [16, 17, 21, 32, 23, 19]]])
print(arr_3)

[[[ 0  1  2  3  4  5]
  [10 11 12 13 14 15]
  [16 17 21 32 23 19]]

 [[ 0  1  2  3  4  5]
  [10 11 12 13 14 15]
  [16 17 21 32 23 19]]

 [[ 0  1  2  3  4  5]
  [10 11 12 13 14 15]
  [16 17 21 32 23 19]]]


In [44]:
# Ranks , rows, columns, matrix shape = 3x6
arr_3.shape

(3, 3, 6)

In [45]:
arr_3.ndim

3

In [46]:
# Number of elements present in ND-array
arr_3.size

54

In [50]:
# Slicing of an Array
arr_3

array([[[ 0,  1,  2,  3,  4,  5],
        [10, 11, 12, 13, 14, 15],
        [16, 17, 21, 32, 23, 19]],

       [[ 0,  1,  2,  3,  4,  5],
        [10, 11, 12, 13, 14, 15],
        [16, 17, 21, 32, 23, 19]],

       [[ 0,  1,  2,  3,  4,  5],
        [10, 11, 12, 13, 14, 15],
        [16, 17, 21, 32, 23, 19]]])

In [54]:
print(arr_3[1][2][4])
print(arr_3[1, 2, 4])

23
23


#### Modify the Data-Type

In [55]:
arr_4 = np.array([11, 23, 34, 45, 56, 67, 78])
arr_4

array([11, 23, 34, 45, 56, 67, 78])

In [56]:
arr_4.dtype

dtype('int32')

In [58]:
# Assigning float to int32 array, it will truncate the decimal part
arr_4[1] = 14.5678
print(arr_4)

[11 14 34 45 56 67 78]


In [59]:
# Change dtype of numpy array
arr_5 = arr_4.astype('float32')

In [60]:
arr_5.dtype

dtype('float32')

In [61]:
arr_5[1] = 13.5678
print(arr_5)

[11.     13.5678 34.     45.     56.     67.     78.    ]


#### Empty Array & Fill Content Value

In [62]:
# dtype = float16, float32, float64
# 6 = size of an array
arr_1 = np.empty(6, dtype = 'float16')
arr_1

array([-4.150e+01,  3.641e-03,  2.843e-05,  0.000e+00,  0.000e+00,
        0.000e+00], dtype=float16)

In [63]:
# fill -7.23 to a numpy array
arr_1.fill(-7.23)
print(arr_1)

[-7.23 -7.23 -7.23 -7.23 -7.23 -7.23]


#### Numpy Array Slicing

In [66]:
# Reshaped to a matrix of 6x6
arr_2 = np.arange(1, 37).reshape(6,6)
arr_2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [67]:
# Slicing works much like standard python slicing
# [row,columns]
arr_2[2,1:5]

array([14, 15, 16, 17])

In [68]:
arr_2[1:-1,1:-1]

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29]])

In [69]:
arr_2[1:5,1:5]

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29]])

In [72]:
arr_3 = np.arange(1, 37).reshape(3,12)
arr_3

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]])

#### Reverse an Array Vector

In [74]:
arr_4 = np.arange(50)
print(arr_4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [75]:
# -1 at step position reverse the numpy array
arr_4 = arr_4[::-1]
arr_4

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [78]:
arr_5 = np.arange(10)
print(arr_5)
reversed_arr = np.flipud(arr_5)
print(reversed_arr)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [79]:
arr_6 = np.arange(1, 37).reshape(6,6)
arr_6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [80]:
# Flip array in Up/Down direction
np.flipud(arr_6)

array([[31, 32, 33, 34, 35, 36],
       [25, 26, 27, 28, 29, 30],
       [19, 20, 21, 22, 23, 24],
       [13, 14, 15, 16, 17, 18],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6]])

In [81]:
# fliplr - Reverse the order of elements along axis = 1(left/right)
np.fliplr(arr_6)

array([[ 6,  5,  4,  3,  2,  1],
       [12, 11, 10,  9,  8,  7],
       [18, 17, 16, 15, 14, 13],
       [24, 23, 22, 21, 20, 19],
       [30, 29, 28, 27, 26, 25],
       [36, 35, 34, 33, 32, 31]])

In [82]:
# flip array - left/right & flip up/down
np.flip(arr_6)

array([[36, 35, 34, 33, 32, 31],
       [30, 29, 28, 27, 26, 25],
       [24, 23, 22, 21, 20, 19],
       [18, 17, 16, 15, 14, 13],
       [12, 11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2,  1]])

#### Array Create Function
    1. np.ones()
    2. np.zeros()

In [83]:
# shape 3 rows & 6 columns
# Create an array filled with 1's
np.ones((3,6), dtype = 'float32')

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [84]:
# application - create an empty / sparse matrix
np.zeros((4,6), dtype = 'float32')

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)

    3. Identity Matrix
        * Generate a N x N Identity Matrix. The Default dtype is float64
        * Diagonal values are 1, non-diagonal are zeros.

In [85]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [86]:
np.identity(7, dtype = 'int8')

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]], dtype=int8)

    4. Empty, Full & Fill

In [88]:
arr_7 = np.empty(6)

In [90]:
arr_7.fill(6.0)
arr_7

array([6., 6., 6., 6., 6., 6.])

In [91]:
# Create an array of shape 10, filled with 6.5
np.full(10, 6.5)

array([6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5])

    5. LinSpace
        * Generate N evenly spaced elements between start and stop (stop last value will be included)

In [92]:
# (start, stop, No. of elements)
# Equally spaced (start, stop, No. of elements)
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [95]:
np.linspace(0, 10, 12).reshape(4,3)

array([[ 0.        ,  0.90909091,  1.81818182],
       [ 2.72727273,  3.63636364,  4.54545455],
       [ 5.45454545,  6.36363636,  7.27272727],
       [ 8.18181818,  9.09090909, 10.        ]])

    6. logspace
    * Generate N evenly spaced elements on a log scale between start and stop (log base = 10)

In [96]:
np.logspace(0, 1, 6, base=10)

array([ 1.        ,  1.58489319,  2.51188643,  3.98107171,  6.30957344,
       10.        ])

#### Exercise 1: Create 2D Array with 1 on the Border & rest position will be zeros. Shape = 10x10

In [106]:
arr_8 = np.ones((10, 10), dtype = 'int8')
arr_8[1:-1,1:-1] = 0
arr_8

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)

In [107]:
# Create 2D Array with 0s on the Border & rest position will be ones. Shape = 10x10
arr_9 = np.zeros((10, 10), dtype = 'int8')
arr_9[1:-1,1:-1] = 1
arr_9

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

#### Exercise 2: Checker Board: Create 8x8 matrix & fill it with 1s & 0s in sequence

In [121]:
arr_10 = np.ones((8,8), dtype = 'int8')
# select every alternative element
arr_10[::2, 1::2] = 0
arr_10[1::2, ::2] = 0
print(arr_10)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [122]:
arr_10 = np.zeros((8,8), dtype = 'int8')
# select every alternative element
arr_10[::2, 1::2] = 1
arr_10[1::2, ::2] = 1
print(arr_10)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### Numpy 
    * Array Calculation Method

In [123]:
arr_11 = np.array([[[1, 2, 4],
                    [4, 5, 6]],
                   [[1, 2, 4],
                    [4, 5, 6]]])
arr_11

array([[[1, 2, 4],
        [4, 5, 6]],

       [[1, 2, 4],
        [4, 5, 6]]])

In [124]:
arr_11.sum()

44

In [125]:
# supply the keyword axis to sum along 0th axis (rowwise)
arr_11.sum(axis = 0)

array([[ 2,  4,  8],
       [ 8, 10, 12]])

In [126]:
# supply the keyword axis to sum along 1st axis (columnwise)
arr_11.sum(axis = 1)

array([[ 5,  7, 10],
       [ 5,  7, 10]])

In [127]:
# min Method
arr_11.min()

1

In [129]:
arr_12 = np.arange(0, 36).reshape(6,6)
arr_12.min()

0

In [131]:
arr_12

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [132]:
arr_12.min(axis = 1)

array([ 0,  6, 12, 18, 24, 30])

In [133]:
arr_12.min(axis = 0)

array([0, 1, 2, 3, 4, 5])

In [134]:
# np.where() returns row index , column index
np.where(arr_12 > 20)

(array([3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5], dtype=int64),
 array([3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5], dtype=int64))

In [135]:
np.where(arr_12 == arr_12.min())

(array([0], dtype=int64), array([0], dtype=int64))

In [146]:
np.where(arr_12 == arr_12.min())[0][0], np.where(arr_12 == arr_12.min())[1][0]

(0, 0)

#### Statistical Array Methods

In [148]:
array_1 = np.array([[[1, 2, 4],
                    [5, 6, 7]],
                   [[1, 2, 4],
                    [5, 6, 7]]])
array_1

array([[[1, 2, 4],
        [5, 6, 7]],

       [[1, 2, 4],
        [5, 6, 7]]])

In [149]:
# mean value - overall
array_1.mean()

4.166666666666667

In [150]:
array_1.mean(axis = 0)

array([[1., 2., 4.],
       [5., 6., 7.]])

In [151]:
array_1.mean(axis = 1)

array([[3. , 4. , 5.5],
       [3. , 4. , 5.5]])

In [153]:
# std deviation - Measures the deviation of sample from its mean
np.std(array_1)

2.1147629234082532

In [154]:
# variance
np.var(array_1)

4.472222222222222

In [156]:
# average() , can be also used for calculating weighted average
np.average(array_1, axis = 0)

array([[1., 2., 4.],
       [5., 6., 7.]])

In [162]:
array_2 = [[3, 7, 11],
          [12, 15, 21]]

In [191]:
np.average(array_2, axis = 0)

array([ 7.5, 11. , 16. ])

In [166]:
np.average(array_2, weights = [1,2], axis = 0)

array([ 9.        , 12.33333333, 17.66666667])

#### Array Broadcasting
    * Numpy array of different dimentionality can be combined in the same expression. Arrays with smaller dimension are broadcasted to match the larger array with copying data.

In [167]:
a = np.ones((3, 5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [173]:
b = np.ones((5, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [174]:
a + b

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [175]:
a = np.ones((3, 5))
# b array is broadcasted on smaller side
b = np.ones((5,))
a + b

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [176]:
# Generate Random Integers
a = np.random.randint(10, 20, size = (3, 5))
a

array([[18, 13, 14, 12, 16],
       [15, 13, 11, 15, 11],
       [18, 16, 17, 14, 12]])

In [177]:
b = np.ones(5, )
b = b.reshape(1,5)
b

array([[1., 1., 1., 1., 1.]])

In [178]:
# b array is streched further to new shape = 3x5
a + b

array([[19., 14., 15., 13., 17.],
       [16., 14., 12., 16., 12.],
       [19., 17., 18., 15., 13.]])

In [183]:
b = np.ones((5,1))
b

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [184]:
a + b

ValueError: operands could not be broadcast together with shapes (3,5) (5,1) 

In [186]:
# Transpose of array b
b1 = b.T

In [187]:
a + b1

array([[19., 14., 15., 13., 17.],
       [16., 14., 12., 16., 12.],
       [19., 17., 18., 15., 13.]])

In [188]:
b

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [189]:
b.T

array([[1., 1., 1., 1., 1.]])

#### Flatten

In [192]:
a = np.random.randint(10, 50, size = (5,3))
a

array([[12, 32, 11],
       [37, 16, 46],
       [24, 37, 34],
       [24, 43, 44],
       [15, 32, 30]])

In [193]:
# flatten converts N-D array to 1-D Array
a.flatten()

array([12, 32, 11, 37, 16, 46, 24, 37, 34, 24, 43, 44, 15, 32, 30])

In [194]:
# ravel flattens N-D Array to 1-D Array
a.ravel()

array([12, 32, 11, 37, 16, 46, 24, 37, 34, 24, 43, 44, 15, 32, 30])

#### Exercise 3: Given 1D Array, negate all elements that falls between value 3 & 8

In [196]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [198]:
num = (arr > 3) & (arr < 8)
arr[num] *= -1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14])